### PR TITLE
Adding Current Path

### PR DESCRIPTION
**Pull request by GuckTubeYT**

### CODE REVIEW

**Comment by GuckTubeYT** [comment]
Is something wrong?

**Comment by DrOreo002** [comment]
I'll do a test then I'll merge it

**Comment by GuckTubeYT** [comment]
> I'll do a test then I'll merge it

okay

**Comment by GuckTubeYT** [comment]
later, i want to try bot.json auto maker (if i can)

**Comment by DrOreo002** [comment]
You do not need to make one

**Comment by GuckTubeYT** [comment]
okay

**Pull request merged**
